parameters:
  FunctionAppDescriptiveName: ''
  PoolName: ''
  RGName: ''
  AzureServiceConnection: ''
  Location: ''
  environment: ''


jobs:
- deployment: 'validate_armtemplate'
  displayName: 'Validate ARM template'
  pool:
    name: '${{ parameters.PoolName }}'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        
        - task: AzureCLI@2
          inputs:
            azureSubscription: '${{ parameters.AzureServiceConnection }}'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az --version
              az group create --name ${{ parameters.RGName }} --location ${{ parameters.Location }}
              az deployment group validate --resource-group ${{ parameters.RGName }} --template-file 'ARMTemplates/Templates/FA_PowerBiAuditLogs.bicep' --parameters 'ARMTemplates/Parameters/${{ parameters.environment }}/FA_PowerBiAuditLogs.parameters.json'

- deployment: 'release_armtemplate'
  dependsOn: 'validate_armtemplate'
  displayName: 'Release ARM template'
  pool:
    name: '${{ parameters.PoolName }}'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        
        - task: AzureCLI@2
          inputs:
            azureSubscription: '${{ parameters.AzureServiceConnection }}'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az --version
              az group create --name ${{ parameters.RGName }} --location ${{ parameters.Location }}
              az deployment group create --resource-group ${{ parameters.RGName }} --template-file 'ARMTemplates/Templates/FA_PowerBiAuditLogs.bicep' --parameters 'ARMTemplates/Parameters/${{ parameters.environment }}/FA_PowerBiAuditLogs.parameters.json' --mode Incremental
