parameters:
  PoolName: ''
  AzureServiceConnection: ''
  environment: ''
  FunctionAppName: ''
  FunctionAppShortName: ''


jobs:
- deployment: 'release_function'
  displayName: 'Release Function Code ${{ parameters.environment }}'
  pool:
    name: '${{ parameters.PoolName }}'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        
        - task: ArchiveFiles@2
          displayName: 'Archiving DeployACIContainer Function'
          inputs:
            rootFolderOrFile: '${{ parameters.FunctionAppShortName }}/'
            includeRootFolder: false
            replaceExistingArchive: true
            archiveFile: '$(System.DefaultWorkingDirectory)/powerbi_function.zip'
        - task: AzureFunctionApp@1
          displayName: 'Azure Function App Deploy'
          inputs:
            azureSubscription: '${{ parameters.AzureServiceConnection }}'
            appName: '${{ parameters.FunctionAppName }}'
            package: '$(System.DefaultWorkingDirectory)/powerbi_function.zip'
            deploymentMode: 'zipDeploy'